[package]
name = "rusty_tongue"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
ringbuf = "0.4.7"
rusqlite = { version = "0.33.0", features = ["bundled"] }
rust-translate = "0.1.3"
tokio = "1.43.0"
