[package]
name = "rusty_tongue"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"
ringbuf = "0.4.7"
ron = "0.8.1"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
